// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfjPuX5GTBHWEyptEWsUn3BhDAQoGwawE',
    appId: '1:612187665184:web:1169074d43af0cd5675d45',
    messagingSenderId: '612187665184',
    projectId: 'duostreaming-a7e93',
    authDomain: 'duostreaming-a7e93.firebaseapp.com',
    storageBucket: 'duostreaming-a7e93.appspot.com',
    measurementId: 'G-0L3YCC8XMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtOv-XZ2lgfUlh6_q7kPyXz24rV2v2Iug',
    appId: '1:612187665184:android:bdfb8a9e4d491dc4675d45',
    messagingSenderId: '612187665184',
    projectId: 'duostreaming-a7e93',
    storageBucket: 'duostreaming-a7e93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk-UuAPyOcAEa1ke1rtFhvzUgf8FVm5us',
    appId: '1:612187665184:ios:955993966fbd4ae9675d45',
    messagingSenderId: '612187665184',
    projectId: 'duostreaming-a7e93',
    storageBucket: 'duostreaming-a7e93.appspot.com',
    iosBundleId: 'com.example.duoStreaming',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk-UuAPyOcAEa1ke1rtFhvzUgf8FVm5us',
    appId: '1:612187665184:ios:949cf6cba5b85ff1675d45',
    messagingSenderId: '612187665184',
    projectId: 'duostreaming-a7e93',
    storageBucket: 'duostreaming-a7e93.appspot.com',
    iosBundleId: 'com.example.duoStreaming.RunnerTests',
  );
}
